# This file contains all available configuration options
# with their default values.
version: "2"
# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.

# output configuration options
# all available settings of specific linters
formatters:
  enable:
    - gofmt
    - goimports
linters:
  enable:
    - errcheck
    - goconst
    - misspell
    - lll
    - unused
    - gocritic
    - ineffassign
    - unconvert
  disable:
    - govet
    - dupl ## JOE Don't want to bother
    - goconst
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - nakedret
    - prealloc
    - exhaustive
    - rowserrcheck # this is completely broken
    - bodyclose # thinks all body closes have to happen in the same function as the request
    - contextcheck # not ready for go1.18 yet
    - nilerr # not ready for go1.18 yet
    - noctx # not ready for go1.18 yet
    - sqlclosecheck # not ready for go1.18 yet
    - staticcheck # not ready for go1.18 yet
    - unparam # not ready for go1.18 yet
    - unused # not ready for go1.18 yet
    - asasalint # a nonsense rule
    - reassign # stupid rule blocking a valid API use
    - revive # complains about unexported return, calling it annoying
    - gosmopolitan # doesn't allow the use of time.Local, strange rule
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-function: fmt:.*,io/ioutil:^Read.*

    govet:
      shadow: true
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    gofmt:
      simplify: true
    goimports:
    gocyclo:
      min-complexity: 10
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    depguard:
      list-type: blacklist
      include-go-root: false
      packages:
        - github.com/davecgh/go-spew/spew
    misspell:
      locale: US
      ignore-words:
        - someword
    lll:
      line-length: 140
      tab-width: 4
    unused:
      check-exported: false
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 60
    prealloc:
      simple: true
      range-loops: true # Report preallocation suggestions on range loops, true by default
      for-loops: false # Report preallocation suggestions on for loops, false by default
    gocritic:
      enabled-checks:
      disabled-checks:
      enabled-tags:
        - performance
      settings: # settings passed to gocritic
        captLocal: # must be valid enabled check name
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - lll
          - goconst
          - noctx

      # Exclude known linters from partially hard-vendored code,
      # which is impossible to exclude via "nolint" comments.
      - path: internal/hmac/
        text: "weak cryptographic primitive"
        linters:
          #- gosec

      # Exclude some staticcheck messages
      - linters:
          - staticcheck
        text: "SA9003:"

      - linters:
          - gocritic
        text: "can combine chain of . appends into one"

      # Exclude lll issues for long lines with go:generate
      - linters:
          - lll
        source: "^//go:generate "
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
